parameters:

  pxfusion_service.class: Heystack\Subsystem\Payment\DPS\PXFusion\Service
  pxfusion_input_processor.class: Heystack\Subsystem\Payment\DPS\PXFusion\InputProcessor
  pxfusion_output_processor.class: Heystack\Subsystem\Payment\DPS\PXFusion\OutputProcessor
  pxfusion_output_processor.completeURL: checkout/thankyou
  pxfusion_output_processor.confirmationURL: 'checkout/confirm'
  pxfusion_output_processor.failureURL: checkout/failure
  pxfusion_payment_response.class: Heystack\Subsystem\Payment\DPS\PXFusion\PaymentResponse

  pxpost_service.class: Heystack\Subsystem\Payment\DPS\PXPost\Service
  pxpost_input_processor.class: Heystack\Subsystem\Payment\DPS\PXPost\InputProcessor
  pxpost_output_processor.class: Heystack\Subsystem\Payment\DPS\PXPost\OutputProcessor
  pxpost_payment_response.class: Heystack\Subsystem\Payment\DPS\PXPost\PaymentResponse

services:

  dataobject_generator:
    class: %dataobject_generator.class%

  pxfusion_service:
    class: %pxfusion_service.class%
    arguments: [ @event_dispatcher, @transaction, @currency_service ]

  pxfusion_input_processor:
    class: %pxfusion_input_processor.class%
    arguments: [ @pxfusion_service, @storage, @state, @transaction ]
    tags:
      - { name: input_processor_handler.processor }

  pxfusion_output_processor:
    class: %pxfusion_output_processor.class%
    arguments: [ %pxfusion_output_processor.completeURL%, %pxfusion_output_processor.confirmationURL%, %pxfusion_output_processor.failureURL% ]
    tags:
      - { name: output_processor_handler.processor }

  pxfusion_payment_response:
    class: %pxfusion_payment_response.class%
    arguments: [ [] ]
    tags:
      - { name: ss_orm_backend.data_provider }

  pxpost_service:
    class: %pxpost_service.class%
    arguments: [ @event_dispatcher, @transaction, @currency_service ]

  pxpost_input_processor:
    class: %pxpost_input_processor.class%
    arguments: [ @pxpost_service ]
    tags:
      - { name: input_processor_handler.processor }

  pxpost_output_processor:
    class: %pxpost_output_processor.class%
    tags:
      - { name: output_processor_handler.processor }

  pxpost_payment_response:
    class: %pxpost_payment_response.class%
    arguments: [ [] ]
    tags:
      - { name: ss_orm_backend.data_provider }

  transaction_pxfusion_payment_schema:
    class: %yaml_data_object_schema.class%
    arguments: [ ecommerce-payment/config/storage/transaction_pxfusionpayment.yml, @state_global ]
    tags:
      - { name: dataobject_generator.schema }

  pxfusion_payment_schema:
    class: %yaml_data_object_schema.class%
    arguments: [ ecommerce-payment/config/storage/pxfusionpayment.yml, @state_global ]
    tags:
      - { name: dataobject_generator.schema }

  pxpost_payment_schema:
    class: %yaml_data_object_schema.class%
    arguments: [ ecommerce-payment/config/storage/pxpostpayment.yml, @state_global ]
    tags:
      - { name: dataobject_generator.schema }

  transaction_pxpost_payment_schema:
    class: %yaml_data_object_schema.class%
    arguments: [ ecommerce-payment/config/storage/transaction_pxpostpayment.yml, @state_global ]
    tags:
      - { name: dataobject_generator.schema }
